# Generated by Django 5.0.7 on 2024-07-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
